name: BertXMLTAE

model:
  hidden_size: 300
  n_aheads: 2
  intermediate_size: 600
  n_layers: 2
  n_probes: 5
  dropout: 0.1
  src_max_len: 500
  emb_trainable: True

train:
  batch_size: 40
  nb_epoch: 30
  swa_warmup: 10

valid:
  batch_size: 40

predict:
  batch_size: 40

path: ../data/citeulike-t/models