name: LstmATT

model:
  hidden_size: 256
  layers_num: 1
  linear_size: [256]
  dropout: 0.5
  emb_trainable: False

train:
  batch_size: 40
  nb_epoch: 100
  swa_warmup: 10


valid:
  batch_size: 40

predict:
  batch_size: 40

path: ../data/EUR-Lex/models